spring:
  application:
    name: greentig-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greentig-service:
  greeting: "Olá Fernando"
  default-value: "Você é um cara legal!"
  
